name: Set up environment
runs:
    using: "composite"
    steps:
        -   name: Set up .NET Core SDK
            uses: actions/setup-dotnet@v5
            with:
                dotnet-version: '9.x'
