name: Set up .NET environment
runs:
    using: "composite"
    steps:
        -   name: Set up .NET Core SDK
            uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
            with:
                dotnet-version: 10.x
        -   name: Cache NuGet packages
            uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
            with:
                path: ${{ github.workspace }}/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
