name: Set up environment
runs:
    using: "composite"
    steps:
        -   name: Set up .NET Core SDK
            uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
            with:
                dotnet-version: '10.x'
        -   name: Set up Node.js
            uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
            with:
                node-version: 'lts/*'
                cache: 'npm'
                cache-dependency-path: './src/SmoothNanners.Web/package-lock.json'
        -   name: Update npm
            shell: bash
            run: npm install -g npm
