name: Set up environment
runs:
    using: "composite"
    steps:
        -   name: Set up .NET Core SDK
            uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
            with:
                dotnet-version: '10.x'
