name: Deploy

on:
    push:
        branches: [ main ]

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    test:
        uses: ./.github/workflows/test.yml
    build:
        needs: [ lint, test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   uses: ./.github/actions/setup-environment
            -   name: Build
                run: dotnet build ./src/SmoothNanners.Web -c Release
            -   name: SSG
                run: dotnet run --project ./src/SmoothNanners.Web -lp ssg -c Release --no-build
            -   name: Upload artifact
                id: deployment
                uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
                with:
                    path: ./src/SmoothNanners.Web/bin/Release/net10.0/ssg
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
