name: Deploy

on:
    push:
        branches: [ master ]

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    analyze:
        uses: ./.github/workflows/codeql.yml
    test:
        uses: ./.github/workflows/test.yml
    deploy:
        needs: [ analyze, test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up .NET Core SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'
            -   name: Build
                run: dotnet publish ./src/SmoothNanners.Web -c Release -o ./out
            -   name: Generate static pages
                working-directory: ./out
                run: dotnet SmoothNanners.Web.dll ssg
            -   name: Deploy to Cloudflare Pages
                uses: cloudflare/wrangler-action@v3
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    command: pages deploy ./out/ssg --project-name=smoothnanners-web
