name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   uses: ./.github/actions/setup-environment
            -   name: Install dependencies
                working-directory: ./src/SmoothNanners.Web
                run: npm ci
            -   name: Lint
                working-directory: ./src/SmoothNanners.Web
                run: npm run lint
