name: Main

on:
    push:
        branches: [ main ]
        paths:
            - '.editorconfig'
            - '*.slnx'
            - 'Directory.Build.props'
            - 'global.json'
            - 'src/**'
            - 'tests/**'
    workflow_dispatch:

concurrency:
    group: main
    cancel-in-progress: true

jobs:
    test:
        uses: ./.github/workflows/test.yml
    build:
        needs: test
        runs-on: ubuntu-latest
        env:
            NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
        steps:
            -   name: Checkout
                uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            -   uses: ./.github/actions/setup-environment
            -   name: Restore dependencies
                run: dotnet restore --locked-mode
            -   name: Cache Libman assets
                uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
                with:
                    path: ~/.local/share/.librarymanager/cache
                    key: ${{ runner.os }}-libman-${{ hashFiles('**/libman.json') }}
            -   name: SSG
                run: dotnet run --project ./src/SmoothNanners.Web --no-restore -c Release -lp ssg
            -   name: Upload artifact
                id: deployment
                uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
                with:
                    path: ./src/SmoothNanners.Web/bin/Release/net10.0/ssg
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
