name: PR

on:
    pull_request:
        branches: [ main ]

jobs:
    pr-test:
        uses: ./.github/workflows/test.yml
    pr-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   uses: ./.github/actions/setup-environment
            -   name: Build
                run: dotnet build ./src/SmoothNanners.Web -c Release
            -   name: SSG
                run: dotnet run --project ./src/SmoothNanners.Web -lp ssg -c Release --no-build
