name: PR

on:
    pull_request:
        branches: [ main ]
        paths:
            - '.editorconfig'
            - 'Directory.Build.props'
            - 'src/**'
            - 'tests/**'

jobs:
    pr-test:
        uses: ./.github/workflows/test.yml
    # Build and verify static site generation succeeds.
    pr-build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   uses: ./.github/actions/setup-environment
            -   uses: ./.github/actions/cache-libman-assets
            -   name: Build
                run: dotnet build ./src/SmoothNanners.Web -c Release
            -   name: SSG
                run: dotnet run --project ./src/SmoothNanners.Web -lp ssg -c Release --no-build
