name: Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   uses: ./.github/actions/setup-environment
            -   name: Get Playwright version
                shell: pwsh
                run: |
                    $csprojPath = "./tests/SmoothNanners.Web.Tests.Integration/SmoothNanners.Web.Tests.Integration.csproj"
                    [xml]$csproj = Get-Content $csprojPath
                    $version = $csproj.Project.ItemGroup.PackageReference |
                      Where-Object { $_.Include -eq "Microsoft.Playwright" } |
                      Select-Object -ExpandProperty Version
                    echo "PlaywrightVersion=$version" >> $env:GITHUB_ENV
            -   name: Cache Playwright browsers
                uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
                with:
                    path: ~/.cache/ms-playwright
                    key: ${{ runner.os }}-playwright-${{ env.PlaywrightVersion }}
            -   name: Test
                run: dotnet test -c Release --results-directory ./test-results -- --report-ctrf
            -   if: always()
                name: Publish test report
                uses: ctrf-io/github-test-reporter@0f299074936c32ccaab5be5230511f6b2b9080aa # v1.0.28
                with:
                    report-path: ./test-results/*.ctrf
                    summary-report: true
                    file-report: true
                    failed-folded-report: true
                    skipped-report: true
