name: Test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up .NET Core SDK
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0.x'
            -   name: Setup Bun
                uses: oven-sh/setup-bun@v2
                with:
                    bun-version: latest
            -   name: Build
                run: dotnet build
            -   name: Setup Playwright
                run: pwsh ./tests/SmoothNanners.Web.Tests.E2E/bin/Debug/net8.0/playwright.ps1 install --with-deps chromium
            -   name: Test
                run: dotnet test --no-build --verbosity normal
